# Generated by Django 5.2.6 on 2025-09-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('surname', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=1)),
                ('birth_date', models.DateField()),
                ('nickname', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('language', models.CharField(max_length=2)),
                ('password', models.CharField(max_length=225)),
                ('card', models.CharField(max_length=16)),
            ],
        ),
    ]
