# Generated by Django 5.2.6 on 2025-10-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='ru', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='m', max_length=1, null=True),
        ),
    ]
