# Generated by Django 5.2.6 on 2025-10-06 21:35

import secured_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_card_user_language_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card',
            field=secured_fields.fields.EncryptedCharField(blank=True, max_length=18, null=True, searchable=True),
        ),
    ]
